{
 "title": "Internet Speed",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Tunnel Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tunnel Upload Speed",
   "type": "timeseries",
   "description": "The tunnel upload speed measured every 10 seconds in Mbps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "TUNNEL_UL" }
   ]
  },
  {
   "title": "Tunnel Download Speed",
   "type": "timeseries",
   "description": "Download speed measured every 10 seconds using perf",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "TUNNEL_DL" }
   ]
  },
  { "title": "Google Load Time (In Seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Google Load Time on Foreign Server",
   "type": "timeseries",
   "description": "The time it takes to load google.com from the foreign server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "FS_RQ_LD_google" },
    { "expr": "FS_RQ_ERR_google" }
   ]
  },
  {
   "title": "Google Load Time on IR Server",
   "type": "timeseries",
   "description": "The time it takes to load google.com from the IR server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "IR_RQ_LD_google" },
    { "expr": "FS_RQ_ERR_google" }
   ]
  },
  { "title": "Youtube Load time (In Seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Youtube Load Time on Foreign Server",
   "type": "timeseries",
   "description": "The time it takes to load youtube.com from the foreign server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "FS_RQ_LD_youtube" },
    { "expr": "FS_RQ_ERR_youtube" }
   ]
  },
  {
   "title": "Youtube Load Time on IR Server",
   "type": "timeseries",
   "description": "The time it takes to load youtube.com from the IR server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "IR_RQ_LD_youtube" },
    { "expr": "IR_RQ_ERR_youtube" }
   ]
  },
  {
   "title": "Instagram Load time (In Seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Instagram Load Time on Foreign Server",
   "type": "timeseries",
   "description": "The time it takes to load instagram.com from the foreign server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "FS_RQ_LD_instagram" },
    { "expr": "FS_RQ_ERR_instagram" }
   ]
  },
  {
   "title": "Instagram Load Time on IR Server",
   "type": "timeseries",
   "description": "The time it takes to load instagram.com from the IR server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "IR_RQ_LD_instagram" },
    { "expr": "IR_RQ_ERR_instagram" }
   ]
  },
  {
   "title": "Facebook Load time (In Seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Facebook Load Time on Foreign Server",
   "type": "timeseries",
   "description": "The time it takes to load facebook.com from the foreign server (doesn't go through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "FS_RQ_LD_facebook" },
    { "expr": "FS_RQ_ERR_facebook" }
   ]
  },
  {
   "title": "Facebook Load Time on IR Server",
   "type": "timeseries",
   "description": "The time it takes to load facebook.com from the IR server (goes through the tunnel).\nThe green line is for the time it takes to get a 200 return code, and if there is an other return code, the yellow line shows it.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    { "expr": "IR_RQ_LD_facebook" },
    { "expr": "IR_RQ_ERR_facebook" }
   ]
  }
 ]
}