---
- name: Setting up OpenVPN Server
  tags:
    - setup_foreign_server
    - setup_foreign_side
    - ubuntu_22_04
  block:
    - name: Setup openvpn on ubuntu server
      debug:
        msg: "OpenVPN on ubuntu: {{ inventory_hostname }}"

    - name: Get peer FQDN
      command: "hostname --fqdn"
      register: peer_fqdn
      delegate_to: "{{ peer | ipaddr('address') }}"
    
    - name: Creating the target working directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ ovpn_root }}"
        - "/run/openvpn_foreign"
    
    - name: Disabling and removing auto-update
      apt:
        name: "unattended-upgrades"
        state: absent
        update_cache: true
    
    - name: Installing openvpn on the host
      ansible.builtin.apt:
        name: "{{ openvpn_ubuntu_package_name }}"
        state: latest
        update_cache: yes

    - name: Installing stunnel on the host
      ansible.builtin.apt:
        name: "{{ stunnel_package_name }}"
        state: latest
        update_cache: yes
      when: setup_stunnel | bool
    
    - name: Make sure the default service is disabled and stopped
      ignore_errors: yes
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - openvpn
        - openvpn-iptables
        - openvpn-foreign
        - stunnel
        - stunnel4

    - name: Fetch the secret file from peer server to ansible
      fetch:
        src: "{{ secret_path }}"
        dest: "/tmp/.secret_{{ peer | ipaddr('address') }}"
        flat: yes
      delegate_to: "{{ peer | ipaddr('address') }}"

    - name: Copy the secret file to the fs server
      copy:
        src: "/tmp/.secret_{{ peer | ipaddr('address') }}"
        dest: "{{ secret_path }}"
        mode: '0400'
        force: yes

    - name: Template systemd service file
      template:
        src: "etc/systemd/system/openvpn-foreign.service"
        dest: "/etc/systemd/system/openvpn-foreign.service"
    
    - name: Enabling ip_forward in sysctl and /proc
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    
    - name: Template the iptables rules service file
      template:
        src: "etc/systemd/system/openvpn-iptables.service"
        dest: "/etc/systemd/system/openvpn-iptables.service"

    - name: Configure Stunnel if setup_stunnel is set
      block:

      - name: Make sure stunnel directory exists under etc
        file:
          path: "/etc/stunnel"
          state: "directory"

      - name: Make sure log and run direcotries exist
        file:
          path: "{{ item }}"
          state: directory
          owner: stunnel4
          group: stunnel4
        loop:
          - "/var/log/stunnel4"
          - "/var/run/stunnel4"

      - name: Template the stunnel config file
        template:
          src: "etc/stunnel/stunnel-ovpn-client.conf"
          dest: "/etc/stunnel/stunnel-ovpn-client.conf"

      - name: Template the stunnel service file
        template:
          src: "etc/systemd/system/stunnel-ovpn-client.service"
          dest: "/etc/systemd/system/stunnel-ovpn-client.service"

      - name: Copy the stunnel peer certificate to the server
        copy:
          src: "/tmp/.stunnel_cert_{{ peer }}.crt"
          dest: "/etc/stunnel/stunnel_peer_cert_{{ peer }}.crt"
          mode: '0400'
          force: yes

      - name: Reload systemd
        systemd:
          daemon-reload: yes
  
      - name: Start Stunnel client service
        systemd:
          name: "stunnel-ovpn-client.service"
          state: started
          enabled: yes

      when: setup_stunnel | bool == true
      
    - name: Enable and start OpenVPN iptables service
      systemd:
        name: "openvpn-iptables"
        state: started
        enabled: yes
    
    - name: Systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: Enable and start openvpn-foreign service
      systemd:
        name: openvpn-foreign
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Check if the peer is reachable
      command: ping -c3 10.200.0.1
      register: ping_result

    - name: Fail if peer is not reachable
      fail:
        msg: "Can't reachout to the peer at 10.200.0.1"
      when: ping_result.rc != 0
    
    - name: Template routecheck service files
      template:
        src: "etc/systemd/system/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      loop:
        - "openvpn-routecheck.service"
        - "openvpn-routecheck.timer"
    
    - name: Systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: Setup systemd-resolved to listen on tun interface
      template:
        src: "etc/systemd/resolved.conf"
        dest: "/etc/systemd/resolved.conf"

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved.service
        state: restarted
        enabled: yes
    
    - name: Enable routecheck timer
      systemd:
        name: openvpn-routecheck.timer
        state: started
        enabled: yes
    
    - name: Template logrotate config
      template:
        src: "etc/logrotate.d/ovpn"
        dest: "/etc/logrotate.d/ovpn"


    - name: Remove local secret file
      delegate_to: 127.0.0.1
      file:
        path: "/tmp/.secret_{{ peer | ipaddr('address') }}"
        state: absent
    
