---
- name: Setup OpenVPN client
  tags:
    - setup_ir_side
    - setup_irclient
    - ubuntu_22_04
  block:

    - name: register fqdn
      command: "hostname --fqdn"
      register: peer_fqdn
      delegate_to: "{{ peers[0] | ipaddr('address') }}"

    - name: Change resolv conf file
      lineinfile:
        line: "nameserver 4.2.2.2"
        path: "/etc/resolv.conf"
        create: true
        state: present
    
    - name: Normal setup fresh start
      when: only_switch_fs|bool == false
      block:
        - name: Setup openvpn on ubuntu server
          debug:
            msg: "Installing OpenVPN on {{ inventory_hostname }}"
        
        - name: Disabling and removing auto-update
          apt:
            name: "unattended-upgrades"
            state: absent
        
        - name: Update apt
          apt:
            update_cache: true
        
        - name: Installing the required packages
          apt:
            name: "{{ item }}"
            state: present
          loop: "{{ required_packages }}"
        
        - name: Creating the target working directory
          file:
            path: "{{ ovpn_root }}"
            state: directory
        
        - name: Running the whole proxy setup for openvpn apt repo
          when: setup_apt_proxy|bool == true
          block:
            - name: Running on the local host
              delegate_to: 127.0.0.1
              block:
              - name: Templating the script locally
                template:
                  src: "tmp/ssh_socks_openvpn.sh"
                  dest: "/tmp/ssh_socks_openvpn.sh"
                  mode: '0755'
              
              - name: Run proxy script
                shell: "/tmp/ssh_socks_openvpn.sh"
                register: command_stat
              
              - name: Removing the local proxy script
                file:
                  path: "/tmp/ssh_socks_openvpn.sh"
                  state: absent
            
            - name: Copy apt config to the host
              template:
                src: "etc/apt/apt.conf.d/80proxy.conf"
                dest: "/etc/apt/apt.conf.d/80proxy.conf"
            
            - name: Adding openvpn http repo to the host and updating cache
              apt_repository:
                repo: "deb [trusted=yes] {{ openvpn_ubuntu_repo_addr }} {{ ansible_distribution_release }} main"
                state: present
                filename: openvpn
                update_cache: yes
            
        - name: Installing openvpn on the host
          apt:
            name: "{{ openvpn_ubuntu_package_name }}"
            state: latest
            update_cache: yes
        
        - name: Make sure the default service is disabled and stopped
          ignore_errors: yes
          systemd:
            name: "{{ item }}"
            state: stopped
            enabled: false
          loop:
            - openvpn
            - openvpn-irclient
            - stunnel
            - stunnel4
            - stunnel-ovpn
        
        - name: Copy secret file to Iran server {{ inventory_hostname }}
          copy:
            src: "/tmp/.secret_{{ inventory_hostname }}"
            dest: "{{ secret_path }}"
            mode: '0400'
            force: yes
        
        - name: Template Openvpn-client service
          template:
            src: "etc/systemd/system/openvpn-irclient.service"
            dest: "/etc/systemd/system/openvpn-irclient.service"
        
        - name: Systemd daemon reload
          systemd:
            daemon-reload: yes
        
        - name: Enabling ip_forward in sysctl and proc
          sysctl:
            name: net.ipv4.ip_forward
            value: '1'
            sysctl_set: yes
            state: present
            reload: yes

        - name: Stop and disable systemd-resolved
          systemd:
            name: systemd-resolved
            state: stopped
            enabled: false

        - name: Template the DNS configs
          template:
            src: "etc/resolv.conf"
            dest: "/etc/resolv.conf"

        - name: Stunnel specific setup
          block:

            - name: Template the stunnel config file
              template:
                src: "etc/stunnel/stunnel-client.conf"
                dest: "/etc/stunnel/stunnel-client.conf"

            - name: Copy the peer certificate for stunnel to the server
              copy:
                src: "/tmp/.stunnel_cert_{{ inventory_hostname }}.crt"
                dest: "/etc/stunnel/stunnel_peer_cert.crt"
                mode: '0400'
                force: yes

    
            - name: Make sure log and run directories exist for stunnel
              file:
                path: "{{ item }}"
                state: directory
                owner: stunnel4
                group: stunnel4
              loop:
                - "/var/log/stunnel4"
                - "/var/run/stunnel4"
    
            - name: Template the stunnel systemd service file
              template:
                src: "etc/systemd/system/stunnel-ovpn.service"
                dest: "/etc/systemd/system/stunnel-ovpn.service"

            - name: Systemd daemon-reload
              systemd:
                daemon-reload: yes

            - name: Start the stunnel service
              systemd:
                name: stunnel-ovpn.service
                state: started
                enabled: yes
            
          when: setup_stunnel|bool == true

            
        - name: Start the client service on iran server
          systemd:
            name: openvpn-irclient
            state: started
            enabled: yes

        - name: Only if there are multiple peers and stunnel is disabled
          block:
            - name: Create text file with peers list
              copy:
                dest: "{{ ovpn_root }}/peers"
                content: "{{ peers | join('\n') }}"

            - name: Template the peer_rotate script
              template:
                src: "opt/ovpn/peer_rotate.sh"
                dest: "{{ ovpn_root }}/peer_rotate.sh"
                mode: '0755'

            - name: Template the peer_rotate service and timer
              template:
                src: "{{ item }}"
                dest: "/{{ item }}"
              loop:
                - "etc/systemd/system/ovpn_peer_rotate.service"
                - "etc/systemd/system/ovpn_peer_rotate.timer"

          when: 
            - peers | length > 1
            - setup_stunnel | bool == false

        - name: Only if there are multiple peers and stunnel is Enabled
          block:
            - name: Create text file with peers list
              copy:
                dest: "{{ ovpn_root }}/peers"
                content: "{{ peers | join('\n') }}"

            - name: Template the peer_rotate_stunnel script
              template:
                src: "opt/ovpn/peer_rotate_stunnel.sh"
                dest: "{{ ovpn_root }}/peer_rotate_stunnel.sh"
                mode: '0755'

            - name: Template the peer_rotate_stunnel service and timer
              template:
                src: "{{ item }}"
                dest: "/{{ item }}"
              loop:
                - "etc/systemd/system/ovpn_peer_rotate_stunnel.service"
                - "etc/systemd/system/ovpn_peer_rotate_stunnel.timer"

          when:
            - peers | length > 1
            - setup_stunnel | bool == true

    
    - name: Only updating the FS related parts
      when: only_switch_fs|bool == true
      block:
        - name: Copy secret file to Iran server {{ inventory_hostname }}
          copy:
            src: "/tmp/.secret_{{ inventory_hostname }}"
            dest: "{{ secret_path }}"
            mode: '0400'
            force: yes
        
        - name: Template Openvpn-client service
          template:
            src: "etc/systemd/system/openvpn-irclient.service"
            dest: "/etc/systemd/system/openvpn-irclient.service"
          when: setup_stunnel|bool == false

        - name: Template the stunnel config
          template:
            src: "etc/stunnel/stunnel-client.conf"
            dest: "/etc/stunnel/stunnel-client.conf"
          when: setup_stunnel|bool == true
        
        - name: Systemd daemon reload
          systemd:
            daemon-reload: yes
  
        - name: Restart OpenVPN client service
          systemd:
            name: openvpn-irclient
            state: restarted
            enabled: yes

    - name: Remove local secret file
      delegate_to: 127.0.0.1
      file:
        path: "/tmp/.secret_{{ inventory_hostname }}"
        state: absent

